### ISSUE TITLE
Cannot apply filters over computed properties

### ISSUE THREAD

**Issue by joelalejandro** [kurierjs/kurier#183]
Using the dummy app, if you try to apply a filter over `voteCount` on the `article` resource, it'll fail because it tries to run the filter over the database.

**Comment by spersico** [comment]
and... what should be the expected behaviour?

**Comment by joelalejandro** [comment]
We can implement this in two stages, depending on other priorities and needs:

1) At the very least, don't mislead the user with a confusing error.

2) A great solution would be to have a native implementation of each comparer to enable the same behaviour databases offer on computed properties.

**Comment by spersico** [comment]
Since #212, a more expressive and clear error is returned now.
