### ISSUE TITLE
Javascript hello world example

### ISSUE THREAD

**Issue by jnfrati** [kurierjs/kurier#261]
I'm trying to do a simple CLI for initializing projects with Kurier, based on what is posted [on this discussion](https://github.com/kurierjs/kurier/discussions/252), I wanted to know if anyone can make a simple Hello World app to be used as a template to initialize the project with no typescript.

**Comment by joelalejandro** [comment]
Hi there @jnfrati!

We now have a JavaScript Starter Pack 🚀 The quickest way to use it for now is via GitHub CLI:

```bash
gh repo create my-api -p kurierjs/kurier-starter-pack-javascript
```

Hopefully the files included there can help you shape up a Kurier CLI :D
