### ISSUE TITLE
Expose `http-utils` to allow custom middleware implementations

### ISSUE THREAD

**Issue by joelalejandro** [kurierjs/kurier#332]
Based on the discussion originated in https://github.com/kurierjs/kurier/discussions/331, there's a useful case for exporting functions in the `http-utils` module, to allow custom server middleware implementations.

**Comment by joelalejandro** [comment]
cc @renanwilliam to keep you posted!

**Comment by marcemira** [comment]
Nice!! Can we please have another alpha package release with this on it? 🙏🏻 thanks a lot @joelalejandro

**Comment by joelalejandro** [comment]
This is now available at `1.3.0-beta1` @marcemira
