### ISSUE TITLE
Transport layer context availability in ApplicationInstance

### ISSUE THREAD

**Issue by joelalejandro** [kurierjs/kurier#334]
It has been demonstrated by productive use cases that we need a way to share transport layer information to the processors (in particular of HTTP transports, such as IP, Host, Origin, Headers).

An example would be a GeocodingProcessor, that receives an `op` with an `address` and returns `latitude` and `longitude`.

Also mentioned in #331.

**Comment by Martinarbez** [comment]
In the meantime, we did this https://github.com/feldico/kurier/pull/3
