### ISSUE TITLE
Add Node 20.x for CI pipeline

### ISSUE THREAD

**Issue by joelalejandro** [kurierjs/kurier#353]
Given that Node.js 20.0.0 will become LTS in October 2023, it'd be nice to get ahead of it and start supporting it.

**Comment by swetag-hash** [comment]
I can start working on it.

**Comment by joelalejandro** [comment]
That's great @swetag-hash! Feel free to start on it.

**Comment by swetag-hash** [comment]
@joelalejandro I have made the required changes as asked for & if anything else is required I am happy to contribute. Do let me know.
